apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  namespace: w255
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      initContainers:
      - name: init-verify-redis-service-dns
        image: busybox:1.36
        command: ['sh', '-c', 'until nslookup redis-service.w255.svc.cluster.local; do echo waiting for redis DNS; sleep 2; done;']
      - name: init-verify-redis-ready
        image: busybox:1.36
        command: ['sh', '-c', 'until printf "PING\r\n" | nc redis-service.w255.svc.cluster.local 6379; do echo waiting for redis; sleep 2; done;']
      containers:
      - name: prediction-api
        image: prediction-api:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: REDIS_URL
          value: "redis://redis-service.w255.svc.cluster.local:6379/0"
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20